general {
    immediate_render = true
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3
    blur_size = 5
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 280, 50
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = true
    inner_color = rgba(30, 30, 46, 0.8)
    font_color = rgba(205, 214, 244, 1.0)
    font_family = Fira Sans Semibold
    outer_color = rgba(137, 180, 250, 0.5)
    outline_thickness = 3
    fade_on_empty = false
    placeholder_text = <i>Parolni kiriting, Farrukh...</i>
    hide_input = false
    rounding = 25
    check_color = rgba(249, 226, 175, 1.0)
    fail_color = rgba(243, 139, 168, 1.0)
    fail_text = <i>XATO: $FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -20
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 5
}

label {
    monitor =
    text = $TIME
    color = rgba(205, 214, 244, 1.0)
    font_size = 90
    font_family = Fira Sans Bold
    position = 0, 150
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 8
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgba(186, 194, 222, 1.0)
    font_size = 20
    font_family = Fira Sans Semibold
    position = 0, 40
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
}

label {
    monitor =
    text =   $LAYOUT
    color = rgba(166, 173, 200, 1.0)
    font_size = 14
    font_family = Fira Sans Semibold
    position = 0, -90
    halign = center
    valign = center
}
