-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    profile = {
        time = "00:00",
        temperature = 5000,
        gamma = 0.8,
    },
})
-- NOTE: Section 'profile' may be a plugin or custom section; verify the output
