-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- TODO: manual review: preload = "local_var_HOME/.config/hypr/assets/blank.png"

-- TODO: manual review: wallpaper = "", "local_var_HOME/.config/hypr/assets/blank.png"

-- TODO: manual review: splash = false
