-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==============================================================================

-- AI CONTEXT:

-- This file handles keyboard layouts, mouse/touchpad settings, and gestures.

-- ==============================================================================

hl.config({
    input = {
        kb_layout = "us,ru,uz",
        kb_options = "grp:alt_shift_toggle",
        numlock_by_default = true,
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            drag_lock = true,
            clickfinger_behavior = true,
            scroll_factor = 0.8,
        },
    },
})

